package org.unical.locations.model;
// Generated 27-Jan-2019 23:44:14 by Hibernate Tools 5.3.6.Final

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int addressid;
	private String buildingname;
	private String streetname;
	private int zipcode;
	private boolean savearea;
	private String descrition;

	public Address() {
	}

	public Address(int addressid, City city, String buildingname, String streetname, int zipcode, boolean savearea,
			String descrition) {
		this.addressid = addressid;
		this.buildingname = buildingname;
		this.streetname = streetname;
		this.zipcode = zipcode;
		this.savearea = savearea;
		this.descrition = descrition;
	}

	public Address(int addressid, String buildingname, String streetname, int zipcode, boolean savearea,
			String descrition) {
		this.addressid = addressid;
		this.buildingname = buildingname;
		this.streetname = streetname;
		this.zipcode = zipcode;
		this.savearea = savearea;
		this.descrition = descrition;
	}

	public int getAddressid() {
		return this.addressid;
	}

	public void setAddressid(int addressid) {
		this.addressid = addressid;
	}

	public String getBuildingname() {
		return this.buildingname;
	}

	public void setBuildingname(String buildingname) {
		this.buildingname = buildingname;
	}

	public String getStreetname() {
		return this.streetname;
	}

	public void setStreetname(String streetname) {
		this.streetname = streetname;
	}

	public int getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(int zipcode) {
		this.zipcode = zipcode;
	}

	public boolean isSavearea() {
		return this.savearea;
	}

	public void setSavearea(boolean savearea) {
		this.savearea = savearea;
	}

	public String getDescrition() {
		return this.descrition;
	}

	public void setDescrition(String descrition) {
		this.descrition = descrition;
	}

}
